In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('iris.data')

Now put heading according to the description mentioned in the dataset

In [3]:
data.columns = ["sepal length", "sepal width", "petal length", "petal width", "Class"]

In [4]:
data.head()

sepal length  sepal width  petal length  petal width        Class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

Make sure that all the datatypes are correct and consistent

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
sepal length    149 non-null float64
sepal width     149 non-null float64
petal length    149 non-null float64
petal width     149 non-null float64
Class           149 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


Dividing the dataset in X and Y (Attributes and Classes)

In [6]:
X = data.drop(['Class'], axis = 1)

In [7]:
Y = data['Class']

In [8]:
X.head()

sepal length  sepal width  petal length  petal width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

In [9]:
Y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Class, dtype: object

Now split the data into training and test data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 0, test_size = 0.30)

In [11]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

__The class prior shows the probability of each class. This can be set before building the model manually. If not then it is handled by the function.In the above cas the priors are not set. So it is adjusted according to the data.__

__The priors adjusted according to the data are as follows__

In [12]:
classifier.class_prior_

array([0.31730769, 0.32692308, 0.35576923])

__Var_smoothing is the portion of the largest variance of all features that is added to variances for calculation stability.In this case the parameter has been set to default.__

In [19]:
classifier.get_params()

{'priors': None, 'var_smoothing': 1e-09}

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
cm = confusion_matrix(y_test, y_pred)

In [15]:
print("Confusion matrix: ", cm)

Confusion matrix:  [[16  0  0]
 [ 0 15  1]
 [ 0  4  9]]


In [16]:
print("Accuracy of the model: " ,accuracy_score(y_test, y_pred))

Accuracy of the model:  0.8888888888888888
